host:ftp2.adeptia.com
port:21
user:qaftp
password:Ftp$QA@Ad3pt!a
SrcFilePath:/bharat/Source/FTP_Source
Src@File:StringFunction.txt
Add On Configurations:
Data@Timeout:30
TrgFilePath:/bharat/Target/FTPS_Target
Trg@fileName:trg.txt
TrgFileName:trg.xls
